apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-zya3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-zya3
    app.kubernetes.io/part-of: httpdtest
  name: devfile-sample-zya3
  namespace: utherp0-tenant
spec:
  path: /
  port:
    targetPort: 3001
  to:
    kind: Service
    name: devfile-sample-zya3
    weight: null
status: {}
